victoria-metrics-k8s-stack:
  enabled: true
  fullnameOverride: "vm"
  victoria-metrics-operator:
    crds:
      plain: true
  alertmanager:
    enabled: true
    config:
      route:
        group_by: ["alertname", "cluster", "service"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        receiver: "telega"
      receivers:
        - name: "telega"
          telegram_configs:
            - api_url: "https://api.telegram.org"
              parse_mode: "HTML"
              message: '{{ template "telegram.default.message" .}}'
              chat_id: ""
              bot_token: ""
    inhibit_rules:
      - target_matchers:
          - severity=~"warning|info"
        source_matchers:
          - severity=critical
        equal:
          - cluster
          - namespace
          - alertname
      - target_matchers:
          - severity=info
        source_matchers:
          - severity=warning
        equal:
          - cluster
          - namespace
          - alertname
      - target_matchers:
          - severity=info
        source_matchers:
          - alertname=InfoInhibitor
        equal:
          - cluster
          - namespace

  templateFiles:
    template_1.tmpl: |-
      {{ define "__yucca_text_alert_list" }}{{ range . }}
      ---
      🪪 <b>{{ .Labels.alertname }}</b>
      {{- if .Annotations.summary }}
      📝 {{ .Annotations.summary }}{{ end }}
      {{- if .Annotations.description }}
      📖 {{ .Annotations.description }}{{ end }}
      🏷 Labels:
      {{ range .Labels.SortedPairs }}  <i>{{ .Name }}</i>: <code>{{ .Value }}</code>
      {{ end }}{{ end }}
      {{ end }}

      {{ define "telegram.yucca.message" }}
      {{ if gt (len .Alerts.Firing) 0 }}
      🔥 Alerts Firing 🔥
      {{ template "__yucca_text_alert_list" .Alerts.Firing }}
      {{ end }}
      {{ if gt (len .Alerts.Resolved) 0 }}
      ✅ Alerts Resolved ✅
      {{ template "__yucca_text_alert_list" .Alerts.Resolved }}
      {{ end }}
      {{ end }}              

  vmalert:
    enabled: true
  grafana:
    plugins:
    - victoriametrics-logs-datasource
    service:
      type: ClusterIP
  defaultDatasources:
    extra:
      - name: VictoriaLogs
        type: victoriametrics-logs-datasource
        url: http://victoria-logs:9428
        access: proxy
        version: 1

  defaultDashboards:
    dashboards:
      alertmanager-overview:
        enabled: false
      etcd:
        enabled: false
      grafana-overview:
        enabled: false
      kubernetes-controller-manager:
        enabled: false
      kubernetes-kubelet:
        enabled: true
      kubernetes-proxy:
        enabled: false
      kubernetes-scheduler:
        enabled: true
      kubernetes-system-api-server:
        enabled: true
      kubernetes-system-coredns:
        enabled: false
      kubernetes-views-global:
        enabled: true
      kubernetes-views-namespaces:
        enabled: true
      kubernetes-views-nodes:
        enabled: true
      kubernetes-views-pods:
        enabled: true
      node-exporter-full:
        enabled: false
      victoriametrics-backupmanager:
        enabled: false
      victoriametrics-cluster:
        enabled: false
      victoriametrics-operator:
        enabled: false
      victoriametrics-single-node:
        enabled: false
      victoriametrics-vmagent:
        enabled: false
      victoriametrics-vmalert:
        enabled: false
  defaultRules:
    create: false

  vmsingle:
    spec:
      resources:
        limits:
          memory: 3Gi
        requests:
          cpu: 100m
          memory: 128Mi
      storage:
        storageClassName: gp2


victoria-logs-single:
  enabled: true
  server:
    fullnameOverride: "victoria-logs"
    retentionPeriod: 7d
    persistentVolume:
      size: 10Gi
      storageClassName: gp2

victoria-logs-collector:
  enabled: true
  remoteWrite:
    - url: http://victoria-logs:9428
  persistence:
    volume:
      emptyDir: {}
  defaultVolumes:
    - name: varlog
      hostPath:
        path: /var/log
  defaultVolumeMounts:
    - name: varlog
      mountPath: /var/log
      readOnly: true


externalDashboards:
  enabled: true
  dashboards:
    logs:
      enabled: true
    hpa:
      enabled: true


defaultRules:
  create: true
  rules:
    network: false
    general: false
    kubeStateMetrics: false
    alertmanager: false

    main: true
    
    k8s: false
    etcd: false
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubelet: false
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeScheduler: false
    node: false
    vmagent: false
    vmsingle: false
    vmhealth: false

  runbookUrl: https://runbooks.prometheus-operator.dev/runbooks
  appNamespacesTarget: ".*"
  labels: {}
  annotations: {}
  additionalRuleLabels: {}

alertmanager:
  enabled: true
  templateFiles:
    template_1.tmpl: |-
      {{ define "__yucca_text_alert_list" }}{{ range . }}
      ---
      🪪 <b>{{ .Labels.alertname }}</b>
      {{- if .Annotations.summary }}
      📝 {{ .Annotations.summary }}{{ end }}
      {{- if .Annotations.description }}
      📖 {{ .Annotations.description }}{{ end }}
      🏷 Labels:
      {{ range .Labels.SortedPairs }}  <i>{{ .Name }}</i>: <code>{{ .Value }}</code>
      {{ end }}{{ end }}
      {{ end }}

      {{ define "telegram.yucca.message" }}
      {{ if gt (len .Alerts.Firing) 0 }}
      🔥 Alerts Firing 🔥
      {{ template "__yucca_text_alert_list" .Alerts.Firing }}
      {{ end }}
      {{ if gt (len .Alerts.Resolved) 0 }}
      ✅ Alerts Resolved ✅
      {{ template "__yucca_text_alert_list" .Alerts.Resolved }}
      {{ end }}
      {{ end }}     