{{- if .Values.app.persistence.secret.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.persistence.secret.name }}-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.app.persistence.secret.externalSecret.secretStoreKind }}
    name: {{ .Values.app.persistence.secret.externalSecret.secretStoreName }}
  target:
    name: {{ .Values.app.persistence.secret.name }}
    creationPolicy: Owner
  data:
    - secretKey: RETAIL_ORDERS_PERSISTENCE_USERNAME
      remoteRef:
        key: {{ .Values.app.persistence.secret.externalSecret.remoteKey }}
        property: username
    - secretKey: RETAIL_ORDERS_PERSISTENCE_PASSWORD
      remoteRef:
        key: {{ .Values.app.persistence.secret.externalSecret.remoteKey }}
        property: password
    - secretKey: RETAIL_ORDERS_PERSISTENCE_ENDPOINT
      remoteRef:
        key: {{ .Values.app.persistence.secret.externalSecret.remoteKey }}
        property: host
    - secretKey: RETAIL_ORDERS_PERSISTENCE_PORT
      remoteRef:
        key: {{ .Values.app.persistence.secret.externalSecret.remoteKey }}
        property: port
{{- end }}
