apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: carts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    namespace: 'carts'
    server: https://kubernetes.default.svc
  source:
    path: src/cart/chart
    repoURL: https://github.com/Andarol/Kubernetes.git
    targetRevision: main
    helm:
      valueFiles:
        - /retail-store/values/carts.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true