apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkout
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    namespace: 'checkout'
    server: https://kubernetes.default.svc
  source:
    path: retail-store/src/checkout/chart
    repoURL: https://github.com/Andarol/Kubernetes.git
    targetRevision: main
    helm:
      valueFiles:
        - /retail-store/values/checkout.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
