---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-db-es
  namespace: catalog
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: catalog-db
    creationPolicy: Owner
  data:
    - secretKey: RETAIL_CATALOG_PERSISTENCE_USER
      remoteRef:
        key: stage-retail-store-catalog-db-credentials
        property: username
    - secretKey: RETAIL_CATALOG_PERSISTENCE_PASSWORD
      remoteRef:
        key: stage-retail-store-catalog-db-credentials
        property: password
    - secretKey: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
      remoteRef:
        key: stage-retail-store-catalog-db-credentials
        property: host

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-rabbitmq-es
  namespace: orders
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: orders-rabbitmq
    creationPolicy: Owner
  data:
    - secretKey: RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME
      remoteRef:
        key: stage-retail-store-mq-credentials
        property: username
    - secretKey: RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD
      remoteRef:
        key: stage-retail-store-mq-credentials
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: checkout-redis-es
  namespace: checkout
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: checkout-redis
    creationPolicy: Owner
  data:
    - secretKey: RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL
      remoteRef:
        key: stage-retail-store-checkout-redis-credentials
        property: url
