apiVersion: v1
kind: Service
metadata:
  name: simple-app-backend
  labels:
    app: simple-app
    component: backend
spec:
  type: ClusterIP
  selector:
    app: simple-app
    component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
