apiVersion: v1
kind: Service
metadata:
  name: demo-app-backend
  labels:
    app: demo-app
    component: backend
spec:
  type: ClusterIP
  selector:
    app: demo-app
    component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
