apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-app-db
  labels:
    app: demo-app
    component: db
spec:
  serviceName: demo-app-db
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      component: db
  template:
    metadata:
      labels:
        app: demo-app
        component: db
    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: demo-app-db
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.db.storage }}
